server:
  port: 29020

spring:
  config:
    import: optional:configtree:/run/secrets/quote/
  cache:
    type: redis
  mail:
    host: smtp.qq.com           # QQ 邮箱 SMTP 服务器
    port: 465                   # QQ 邮箱 SSL 端口
    username: 1435208701@qq.com     # 你的完整 QQ 邮箱
    password: xtamqrxqbpfubacc
    protocol: smtp
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            enable: true        # 必须开启 SSL，QQ 邮箱强制要求
            trust: smtp.qq.com
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
            fallback: false
  application:
    name: mogo-project
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mogo_db?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true
    username: root
    password: 123 # ⚠️ 修改这里
  # Redis 配置
  data:
    redis:
      host: localhost
      port: 6379
      password: # 如果有密码请填写
      database: 0


# MyBatis Plus 配置
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: deleteFlag  # 实体类里的字段名
      logic-delete-value: 1        # 删除后的值 (RuoYi习惯用2)
      logic-not-delete-value: 0    # 未删除的值
  mapper-locations: classpath*:mapper/**/*.xml
  type-aliases-package: com.mogo.project.modules.**.entity # 扫描实体类
  configuration:
    map-underscore-to-camel-case: true # 开启驼峰命名转换
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 自定义 JWT 配置 (后续在代码中读取)
jwt:
  header: Authorization
  secret: abcdefghijklmnopqrstuvwxyz0123456789abcdef # ⚠️ 必须足够长(32+字符)用于 HS256 算法
  access-token-expiration: 3000 #1800000 #3000 token30分钟
  refresh-token-expiration: 2000000 #604800000 #20000 刷新token 7天
knife4j:
  enable: true
  setting:
    language: zh_cn
minio:
  endpoint: http://localhost:9000
  access-key: admin
  secret-key: admin123
  bucket-name: mogo
aviator:
  #公式计算
  # 是否强制将小数解析为 BigDecimal (true/false)
  parse-decimal: true
  # 计算精度: DECIMAL32, DECIMAL64, DECIMAL128, UNLIMITED
  math-context: DECIMAL128
dingtalk:
  app-key: "1"
  app-secret: "2"
  space-id: "3"
  target-folder-id: "0"
  operator-union-id: "4"
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    health:
      show-details: when_authorized
client-error:
  security:
    allow-anonymous: true
    # 单位：秒，签名允许时间窗
    sign-window-seconds: 300
    # 每分钟每 IP + appName 最大上报次数
    max-per-minute: 120
    # appKey:appSecret,appKey2:appSecret2
    app-secrets: "web-portal:replace-with-strong-secret"
  alert:
    # 同类错误 5 分钟阈值（达到后告警）
    threshold-5m: 30
  archive:
    # 热数据保留天数（建议 30~90 天）
    retention-days: 90



